### ISSUE TITLE
Discord invitation seems to have expired

### ISSUE THREAD

**Issue by jkitchin** [dungeon-mode/game#3]
https://discord.gg/gar8ns doesn't seem to work anymore.

**Comment by mplscorwin** [comment]
Updated, thanks.

**Comment by mplscorwin** [comment]
Bah. missed the tag on the commit so manually adding the commit link: 
`291524e` https://github.com/dungeon-mode/game/commit/291524ef41af84dcc348d117b253e2a6af71cb53
